# ====================== SYNTAX ======================

"comment" = { fg = "fg-subtle" }

"operator" = { fg = "blue" }
"punctuation" = { fg = "blue" }
"punctuation.bracket" = { fg = "fg-subtle" }

"string" = { fg = "orange", modifiers = ["italic"] }
"constant" = { fg = "magenta" }
"constant.character" = { fg = "orange" }
"constant.character.escape" = { fg = "magenta" }

"keyword" = { fg = "magenta" }

# ====================== MARKUP ======================

"markup.bold" = { fg = "magenta", modifiers = ["bold"] }
"markup.italic" = { fg = "magenta", modifiers = ["italic"] }
"markup.strikethrough" = { fg = "fg-subtle", modifiers = ["crossed_out"] }

"markup.heading" = { fg = "orange", bg = "fg-subtle-alt" }
"markup.raw" = { bg = "fg-subtle-alt" }
"markup.quote" = { fg = "fg" }

"markup.list" = { fg = "blue" }
"markup.list.checked" = { fg = "fg-subtle", modifiers = ["crossed_out"] }

"markup.link" = { fg = "blue", underline = { style = "line" } }

# ======================== UI ========================

"ui.background" = { fg = "fg-subtle", bg = "bg" }

"ui.cursor" = { fg = "bg", bg = "fg" }
"ui.cursor.match" = { fg = "blue" }
"ui.cursor.primary" = { fg = "bg", bg = "blue" }
"ui.cursor.primary.select" = { fg = "bg", bg = "fg-subtle" }

"ui.linenr.selected" = { fg = "blue" }

"ui.statusline" = { fg = "orange", bg = "bg-subtle" }
"ui.bufferline" = { fg = "fg-subtle", bg = "bg-subtle" }
"ui.bufferline.active" = { fg = "orange", bg = "bg" }

"ui.popup" = { bg = "bg" }
"ui.picker.header.column.active" = { fg = "orange" }
"ui.help" = { fg = "fg", bg = "bg" }

"ui.text" = { fg = "fg" }
"ui.text.focus" = { fg = "orange", bg = "bg-subtle" }

"ui.virtual.ruler" = { bg = "bg-subtle" }
"ui.virtual.whitespace" = { fg = "fg-subtle-alt" }
"ui.virtual.indent-guide" = { fg = "fg-subtle" }
"ui.virtual.inlay-hint" = { fg = "fg-subtle" }
"ui.virtual.wrap" = { fg = "fg-subtle-alt" }
"ui.virtual.jump-label" = { modifiers = ["reversed"] }

"ui.menu" = { fg = "fg", bg = "bg" }
"ui.menu.selected" = { fg = "orange", bg = "bg-subtle" }
"ui.menu.scroll" = { fg = "orange", bg = "bg-subtle" }

"ui.selection" = { bg = "bg-subtle" }

"diagnostic.error" = { fg = "red", underline = { style = "curl" } }
"diagnostic.warning" = { fg = "yellow", underline = { style = "curl" } }
"diagnostic.info" = { fg = "green", underline = { style = "curl" } }
"diagnostic.hint" = { fg = "green", underline = { style = "curl" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

"error" = { fg = "red" }
"warning" = { fg = "yellow" }
"info" = { fg = "green" }
"hint" = { fg = "green" }

"diff.plus" = { fg = "green" }
"diff.minus" = { fg = "red" }
"diff.delta" = { fg = "yellow" }

# ====================== COLORS ======================

[palette]
fg = "#b5b2b0"
fg-subtle = "#4c4b49"
fg-subtle-alt = "#302D2B"

bg = "#1c1917"
bg-subtle = "#252220"

red = "#a88a8a"
yellow = "#a8a18a"
green = "#8aa88a"
blue = "#958aa8"
magenta = "#a88aa6"
orange = "#a8968a"
