inherits = "blight"

[palette]
foreground = "#b3b3b3"
foreground-subtle = "#4d4d4d"

background = "#000000"
background-subtle = "#101010"
background-highlight = "#222433"

red = "#b37474"
yellow = "#b3a374"
green = "#74b389"

accent-1 = "#747eb3"
accent-2 = "#74a3b3"
accent-3 = "#74a3b3"
