# ====================== SYNTAX ======================

"comment" = { fg = "text-subtle" }

"operator" = { fg = "blue" }
"punctuation" = { fg = "blue" }
"punctuation.bracket" = { fg = "text-subtle" }

"string" = { fg = "text-subtle", modifiers = ["italic"] }
"constant" = { fg = "blue" }
"constant.character" = { fg = "text-subtle" }

"keyword" = { fg = "blue" }

# ====================== MARKUP ======================

"markup.bold" = { fg = "blue", modifiers = ["bold"] }
"markup.italic" = { fg = "blue", modifiers = ["italic"] }
"markup.strikethrough" = { fg = "text-subtle", modifiers = ["crossed_out"] }

"markup.heading" = { bg = "blue-subtle" }
"markup.raw" = { bg = "blue-subtle" }
"markup.quote" = { fg = "text" }

"markup.list" = { fg = "blue" }
"markup.list.checked" = { fg = "text-subtle", modifiers = ["crossed_out"] }

"markup.link" = { fg = "blue", underline = { style = "line" } }

# ======================== UI ========================

"ui.background" = { fg = "text-subtle", bg = "background" }

"ui.cursor" = { fg = "background", bg = "text" }
"ui.cursor.match" = { fg = "blue" }
"ui.cursor.primary" = { fg = "text", bg = "blue" }
"ui.cursor.primary.select" = { fg = "white", bg = "text-subtle" }

"ui.linenr.selected" = { fg = "blue" }

"ui.statusline" = { fg = "text", bg = "background-subtle" }
"ui.bufferline" = { fg = "text-subtle", bg = "background-subtle" }
"ui.bufferline.active" = { fg = "blue", bg = "background" }

"ui.popup" = { bg = "background" }
"ui.picker.header.column.active" = { fg = "blue" }
"ui.help" = { fg = "text", bg = "background" }

"ui.text" = { fg = "text" }
"ui.text.focus" = { fg = "blue", bg = "background-subtle" }

"ui.virtual.ruler" = { bg = "background-subtle" }
"ui.virtual.whitespace" = { fg = "text-subtle" }
"ui.virtual.indent-guide" = { fg = "text-subtle" }
"ui.virtual.inlay-hint" = { fg = "text-subtle" }
"ui.virtual.wrap" = { fg = "text-subtle" }
"ui.virtual.jump-label" = { modifiers = ["reversed"] }

"ui.menu" = { fg = "text", bg = "background" }
"ui.menu.selected" = { fg = "blue", bg = "background-subtle" }
"ui.menu.scroll" = { fg = "blue", bg = "background-subtle" }

"ui.selection" = { bg = "background-subtle" }

"diagnostic.error" = { fg = "red", underline = { style = "curl" } }
"diagnostic.warning" = { fg = "yellow", underline = { style = "curl" } }
"diagnostic.info" = { fg = "green", underline = { style = "curl" } }
"diagnostic.hint" = { fg = "green", underline = { style = "curl" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

"error" = { fg = "red" }
"warning" = { fg = "yellow" }
"info" = { fg = "green" }
"hint" = { fg = "green" }

"diff.plus" = { fg = "green" }
"diff.minus" = { fg = "red" }
"diff.delta" = { fg = "yellow" }

# ====================== COLORS ======================

[palette]
text = "#b3b3b3"
text-subtle = "#4d4d4d"

background = "#000000"
background-subtle = "#101010"

red = "#b37474"
yellow = "#b3a374"
green = "#74b389"
blue = "#747eb3"
blue-subtle = "#222433"
