# ====================== SYNTAX ======================
"comment" = { fg = "text-highlight", modifiers = ["dim"] }
"operator" = { fg = "blue" }
"punctuation" = { fg = "blue" }
"string" = { fg = "text-highlight", modifiers = ["italic"] }

# ======================== UI ========================
"ui.background" = { fg = "text-subtle", bg = "background" }

"ui.cursor" = { fg = "background", bg = "text" }
"ui.cursor.match" = { fg = "text-highlight", bg = "background-highlight" }
"ui.cursor.primary" = { fg = "background-highlight", bg = "text-highlight" }

"ui.linenr.selected" = { fg = "text" }

"ui.statusline" = { fg = "text", bg = "background-subtle" }
"ui.bufferline" = { fg = "text", bg = "background-subtle" }
"ui.bufferline.active" = { fg = "text-highlight", bg = "background-highlight" }

"ui.popup" = { bg = "background-subtle" }
"ui.picker.header.column.active" = { fg = "text-highlight" }
"ui.help" = { fg = "text", bg = "background-subtle" }

"ui.text" = { fg = "text" }
"ui.text.focus" = { fg = "text-highlight", bg = "background-highlight" }

"ui.virtual.ruler" = { bg = "background-subtle" }
"ui.virtual.whitespace" = { fg = "text-subtle" }
"ui.virtual.indent-guide" = { fg = "text-subtle" }
"ui.virtual.inlay-hint" = { fg = "text-subtle" }
"ui.virtual.wrap" = { fg = "text-subtle" }
"ui.virtual.jump-label" = { fg = "text-highlight", bg = "background-highlight" }

"ui.menu" = { fg = "text", bg = "background-subtle" }
"ui.menu.selected" = { fg = "text-highlight", bg = "background-highlight" }
"ui.menu.scroll" = { fg = "text-subtle", bg = "background-subtle" }

"ui.selection" = { bg = "background-highlight" }

"diagnostic.error" = { underline = { color = "red", style = "curl" } }
"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }
"diagnostic.info" = { underline = { color = "blue", style = "curl" } }
"diagnostic.hint" = { underline = { color = "magenta", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

"error" = { fg = "red" }
"warning" = { fg = "yellow" }
"info" = { fg = "blue" }
"hint" = { fg = "magenta" }

"diff.plus" = { fg = "green" }
"diff.minus" = { fg = "red" }
"diff.delta" = { fg = "yellow" }

# ====================== COLORS ======================
[palette]
text = "#b5b2b0"
text-subtle = "#4c4b49"
text-highlight = "#a8968a"

background = "#1c1917"
background-subtle = "#252220"
background-highlight = "#302D2B"

red = "#a88a8a"
yellow = "#a8a18a"
green = "#8aa88a"
blue = "#958aa8"
magenta = "#a88aa6"
