inherits = "meliora"

"ui.bufferline.active" = { bg = "magenta", fg = "black" }

"ui.statusline.normal" = { bg = "magenta", fg = "black" }
"ui.statusline.insert" = { bg = "yellow", fg = "black" }
"ui.statusline.select" = { bg = "red", fg = "black" }

"diff.plus" = { fg = "magenta" }
"diff.delta" = { fg = "yellow" }

"ui.virtual.jump-label" = { modifiers = ["bold", "italic", "reversed"] }
